# Generated by Django 4.0 on 2025-06-06 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recepient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='fullname')),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone_number')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
