# Generated by Django 4.0 on 2025-06-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepient',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
