# Generated by Django 4.0 on 2025-06-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='humidity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='humidity'),
        ),
        migrations.AddField(
            model_name='logs',
            name='temperature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='temperature'),
        ),
    ]
