# Generated by Django 4.0 on 2025-06-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videologs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='VideoLogs',
        ),
    ]
